name: Build/test/deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-quality-checks:
    name: 📋  Run quality checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules from cache
        id: cache-node-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Prettier
        run: yarn prettier:check

      - name: Run linters
        run: yarn lint

      - name: Run type check
        run: yarn tsc

  run-tests:
    name: 🧪  Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore node_modules from cache
        id: cache-node-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Build
        run: yarn lambda:build

      - name: Run all tests
        run: yarn test

  deploy:
    name: 🛳 Deploy Stack via CDK
    # needs: [run-tests, run-quality-checks]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}

    steps:
      - uses: actions/checkout@v2

      - name: Restore node_modules from cache
        id: cache-node-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build
        run: yarn lambda:build

      - name: Block concurrent runs
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          yarn lambda:deploy \
            --context apiKey=${{ secrets.DATABASE_API_KEY }} \
            --context recipientEmails=${{ secrets.RECIPIENT_EMAILS }}

  smoke-test:
    name: 💨 Smoke Test
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test get endpoint
        run: ./tools/smoke.sh
